# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    # if we want to sign containers, we need to revert this and implement different solution
    # https://github.com/containers/image/issues/1634
    tags:
      - containers_image_openpgp
    main: ./cmd/ctrlc
    binary: ctrlc
    ldflags:
      - -s -w
      - -X github.com/ctrlplanedev/cli/cmd/ctrlc/root/version.Version={{.Version}}
      - -X github.com/ctrlplanedev/cli/cmd/ctrlc/root/version.GitCommit={{.Commit}}
      - -X github.com/ctrlplanedev/cli/cmd/ctrlc/root/version.BuildDate={{.Date}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      ctrlc_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
